### PR TITLE
airbnb style eslint adjustments

### PR DESCRIPTION
**Pull request by calvinschmidt**
I tried to solve as many linter suggestions as possible, according to: https://eslint.org/docs/rules/

### CODE REVIEW

**Comment by nschoen** [comment]
Thank you, I will have a look. One request in advance: Can you configure the `.js` extension as an allowed `jsx-filename-extension`? See https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md

**Comment by captainsano** [comment]
@calvinschmidt where are the `.snap` files? If they are something like `.swap`, please add it to .gitignore

**Comment by captainsano** [comment]
Otherwise things looks great 👍

**Comment by calvinschmidt** [comment]
@captainsano The snapshot files are recommended to be committed: https://jestjs.io/docs/en/snapshot-testing
@nschoen Thanks for the link. I added the rule.

**Review by captainsano — APPROVED** [review]

**Pull request merged**
